### PR TITLE
[INTER-421] feat: remove hard-coded proxy endpoints, introduce config in build

### PR DESCRIPTION
**Pull request by TheUnderScorer**
- Introduce config with URLs to our APIs, similar to how it is done in CloudFront and Azure integration
- Introduce a check in the build process that fails whenever any required env variable is missing

### CODE REVIEW

**Comment by necipallef** [comment]
Can I ask why are we making this change? The URLs never change (if they change, it would be a breaking change for other libraries), we add complexity to the codebase and build process, and it is now harder to read and debug the code.

**Review by ilfa — APPROVED** [review]

**Comment by Orkuncakilkaya** [comment]
Why we keep this URLs in build environment but not in worker environment?
Let's imagine a scenario that our URLs change, do we need to publish a new version with new URLs?
What if we used worker env instead so users can update their CDN and Ingress URL from their dashboard?

**Comment by ilfa** [comment]
We will need a configurable endpoint at least for proper e2e testing

**Comment by TheUnderScorer** [comment]
@necipallef, in addition to what @ilfa said, it's also to make it consistent with CloudFront, and Azure proxy integrations.

These URLs will rarely change, but having the option to configure them on build time makes it easier to run E2e tests, and to use in different environments (e.g on staging)

**Comment by necipallef** [comment]
> it's also to make it consistent with CloudFront, and Azure proxy integrations.

Why didn't we make these integrations consistent with Cloudflare Integration? Cloudflare was the first to be released. Also, if we had hard-coded endpoints like Cloudflare, we wouldn't need extra build steps that are error-prone. @TheUnderScorer 

> We will need a configurable endpoint at least for proper e2e testing

I don't really understand how it is not possible to run e2e tests with hard-coded URLs. We run e2e tests all the time. @ilfa

**Comment by necipallef** [comment]
Also, I noticed there are PRs for CloudFront, Azure, and Cloudflare but not for the Akamai. Why is that?

**Comment by TheUnderScorer** [comment]
Basing on slack discussion, I'll close this PR for draft for now, until we'll decide to use different URLs for E2E tests

**Pull request closed without merging**
